# 1. Definimos la plataforma mínima (Requisito: 15.6)
platform :ios, '15.6'

# Desactivamos estadísticas de CocoaPods para que vaya más rápido
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig and running flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # 2. Bloque mágico para forzar iOS 15.6 y blindar los permisos
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      
      target.build_configurations.each do |config|
        # Forzamos la versión mínima de despliegue
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
        
        # Configuración CRÍTICA para permission_handler (Evita rechazo de Apple)
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          
          # IMPORTANTE: Aquí le decimos a iOS 
          # Como tu app principal usa local_auth (que se manda solo), dejamos los demás apagados.
          
          ## dart: PermissionGroup.camera
          # 'PERMISSION_CAMERA=1',
          
          ## dart: PermissionGroup.photos
          # 'PERMISSION_PHOTOS=1',
          
          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          # 'PERMISSION_LOCATION=1',
          
          ## dart: PermissionGroup.notification
          # 'PERMISSION_NOTIFICATIONS=1',
        ]
      end
    end
  end
end